### ISSUE TITLE
Missing option to specify the worker file location

### ISSUE THREAD

**Issue by power-media** [JBtje/vite-vue3pdf#1]
Would you add please the option to specify the worker location, instead of default '/pdfjs/pdf.worker.js'?
If possible ASAP as it's urgent for me.
Thanks!

**Comment by JBtje** [comment]
Would you happen to have a pull request i can merge, to make this happen?

**Comment by power-media** [comment]
I have the proposed code change - how to push it to your repo?

**Comment by JBtje** [comment]
- Make a fork of the project
- Make the changes in your own fork
- Test the changes
- Do a pull request, so I can pull your code in
- (remove your own fork if its no longer needed)

**Comment by power-media** [comment]
Thanks.
Pull request created.

**Comment by JBtje** [comment]
Thank you for the pull request. I checked the changed and tested it locally w/o problem.
The package has been published and can be downloaded as version 0.2.0

**Comment by power-media** [comment]
Thank you for quick merging, i am already using updated functionality.
All the best!
